dist: trusty
language: c

addons:
  apt:
    packages:
      - gcc-arm-none-eabi

script:
  - arm-none-eabi-gcc --version
  - make

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
