export ARM_PREFIX=arm-none-eabi-
export CC=$(ARM_PREFIX)gcc
export LD=$(ARM_PREFIX)ld
export AR=$(ARM_PREFIX)ar
export OBJCOPY=$(ARM_PREFIX)objcopy
export INCLUDE_DIR=$(realpath include/)
export COMMON_FLAGS=-Wall -Wextra -nostdlib -nostartfiles -fpic -g
export CC_FLAGS=$(COMMON_FLAGS) -std=gnu99 -ffreestanding -I$(INCLUDE_DIR)
export ASM_FLAGS=$(COMMON_FLAGS)
export LD_FLAGS=
